name: Build and Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: 22

    - name: Install dependencies
      run: npm ci

    - name: Build Nuxt project
      run: npm run build

    - name: Prepare deploy folder
      run: |
        mkdir deploy
        cp -r .output package.json package-lock.json deploy/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: nuxt-build
        path: deploy/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: nuxt-build
        path: deploy/

    - name: Deploy to server
      uses: appleboy/ssh-action@v1.2.2
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          BUILD_PATH=${{ secrets.BUILD_PATH }}
          CONTENT_PATH=${{ secrets.CONTENT_PATH }}

          mkdir -p "$BUILD_PATH"
          mkdir -p "$CONTENT_PATH"

          rm -rf "$BUILD_PATH"/*
          cp -r /tmp/nuxt-deploy/* "$BUILD_PATH"

          docker rm -f nuxt-app || true
          docker run -d \
            --name nuxt-app \
            -v "$BUILD_PATH":/app \
            -v "$CONTENT_PATH":/app/content \
            -w /app \
            -p $PORT:3000 \
            node:22-alpine \
            sh -c "npm ci && node .output/server/index.mjs"
