name: Publish

on: workflow_dispatch

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Update repo
        uses: actions/checkout@v3
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Publish
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "bash /home/megameow/MegaMeow.ru/update.sh"